<a href="https://colab.research.google.com/github/Kusuma-1309/Neural-Networks-and-Deep-Learning/blob/main/modules_of_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Shape-Explains how the data is arranged in a tensor,it also describes the number of elements in each dimension of the tensor

In [12]:
import tensorflow as tf

a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

print(a)
print("Shape:", a.shape)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)


Broadcasting-helps in arithemetic operation of different shapes by increasing the size of the tensor

In [13]:
import tensorflow as tf

a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

b = tf.constant([10, 20, 30])

c = a + b   # broadcasting

print(c)


tf.Tensor(
[[11 22 33]
 [14 25 36]], shape=(2, 3), dtype=int32)


Reshaping-helps in changing the shape of the tensor without altering its data

In [15]:
import tensorflow as tf

a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

reshaped = tf.reshape(a, (3, 2))

print(reshaped)
print("New Shape:", reshaped.shape)


tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
New Shape: (3, 2)


Transpose-it helps in converting the rows into columns,it flips tensor dimensions by interchanging the axes

In [16]:
import tensorflow as tf

a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

transposed = tf.transpose(a)

print(transposed)
print("Transposed Shape:", transposed.shape)


tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
Transposed Shape: (3, 2)



tf.dtypes-is used to define and convert the data type of tensors in TensorFlow.



In [1]:
import tensorflow as tf
x = tf.constant([10, 20, 30], dtype=tf.int32)
y = tf.dtypes.cast(x, tf.float32)
print("Original tensor:", x)
print("Original dtype:", x.dtype)
print("Casted tensor:", y)
print("Casted dtype:", y.dtype)


Original tensor: tf.Tensor([10 20 30], shape=(3,), dtype=int32)
Original dtype: <dtype: 'int32'>
Casted tensor: tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
Casted dtype: <dtype: 'float32'>


tf.constant is a TensorFlow function used to create tensors with fixed  values, and the tensor’s data type is handled using tf.dtypes.

In [2]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


A matrix is created using tf.constant, where the tensor’s data type is explicitly defined using the dtype parameter from TensorFlow’s dtype system.

In [3]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [8]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]


tf.RaggedTensor-used to represent data with variable-length dimensions, such as sentences with different numbers of words or sequences of unequal size, in TensorFlow

In [9]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [10]:
print(ragged_tensor.shape)

(4, None)


tf.string-used to represent data with variable-length dimensions, such as sentences with different numbers of words or sequences of unequal size, in TensorFlow.

In [11]:
import tensorflow as tf
text = tf.constant("Hello TensorFlow", dtype=tf.string)
print(text)
print(text.dtype)


tf.Tensor(b'Hello TensorFlow', shape=(), dtype=string)
<dtype: 'string'>
