<a href="https://colab.research.google.com/github/Kusuma-1309/Neural-Networks-and-Deep-Learning/blob/main/tensor_and_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

perform element-wise addition on two(2,3) tensors filled with random values using Tensor flow

In [1]:
import tensorflow as tf

# Create two (2,3) tensors with random values
tensor1 = tf.random.uniform(shape=(2, 3))
tensor2 = tf.random.uniform(shape=(2, 3))

# Element-wise addition
result = tf.add(tensor1, tensor2)

# Display results
print("Tensor 1:\n", tensor1.numpy())
print("\nTensor 2:\n", tensor2.numpy())
print("\nElement-wise Addition Result:\n", result.numpy())


Tensor 1:
 [[0.66344154 0.26640356 0.30223095]
 [0.3720137  0.13279855 0.89437544]]

Tensor 2:
 [[0.17333817 0.584255   0.4345199 ]
 [0.8147783  0.5913935  0.10236585]]

Element-wise Addition Result:
 [[0.8367797  0.85065854 0.73675084]
 [1.186792   0.724192   0.9967413 ]]


perform element-wise addition on two(2,3) tensors filled with random values using numpy

In [2]:
import numpy as np

# Create two (2,3) arrays with random values
array1 = np.random.rand(2, 3)
array2 = np.random.rand(2, 3)

# Element-wise addition
result = np.add(array1, array2)

# Display results
print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nElement-wise Addition Result:\n", result)


Array 1:
 [[0.93124523 0.14117809 0.25574247]
 [0.6275632  0.76512352 0.77485762]]

Array 2:
 [[0.5449662  0.12454366 0.28169801]
 [0.90592566 0.56302783 0.12270708]]

Element-wise Addition Result:
 [[1.47621143 0.26572175 0.53744047]
 [1.53348886 1.32815135 0.8975647 ]]
